language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - jonathan12352@hotmail.com
    on_success: always
    on_failure: always
branches:
  only:
   - development
before_script:
  - npm install -g @angular/cli
  - npm audit
  
script:
  - ng lint
  - ng build --prod --base-href https://jonathan12352.github.io/bitcoin-order-app/
  after_success:
    - git push master :development
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/bitcoin
  edge: true
  on:
    branch: development