language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - jonathan12352@hotmail.com
    on_success: always
    on_failure: always
branches:
  only:
   - development
before_script:
  - npm install -g @angular/cli
  - npm i @angular-devkit/build-angular@0.803.24
  - npm audit fix
  
script:
  - ng lint
  - ng build --prod --base-href https://jonathan12352.github.io/bitcoin-order-app/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/bitcoin
  edge: true
  on:
    branch: development

after_success:
  - git config --global user.email "jonathan12352@hotmail.com"
  - git config --global user.name "jonathan12352"
  - git remote add origin https://$GITHUB_TOKEN@github.com/jonathan12352/bitcoin-order-app.git
  - git push origin development:master